application:
  name: EmployeeDetails

server:
  port: 9090

## h2 Database
spring:
  database:
    url:  jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform:  org.hibernate.dialect.H2Dialect

  # Enabling H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console